channels:
  - pytorch-nightly
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:

  ############# ESSENTIALS ################
  #      Do not remove any of these
  #########################################

  - python >= 3.9
  - pip
  - pip:
    - -r requirements.txt

  # Cuda & Buildtools
  - cudatoolkit = 11.8  # we need to specifiy this for nccl, because pytorch-cuda and nccl use different cuda packages
  - cuda
  - cxx-compiler >= 1.5
  - cmake >= 3.20

  # Torch
  - pytorch
  - pytorch-cuda = 11.8

  - torchvision
  - torchaudio
  - torchdata >= 0.6

  # MPI & NCCL
  - openmpi-mpicxx
  - mpi4py
  - ucx  # UCX support for OpenMPI
  - nccl >= 2.15.5 # <- might cause cuda incompability issues because it does not take into account
                    #    the cuda version. Thus we MUST fixate the version


  ################ OPTIONAL DEPENDENCIES ##################
  # Feel free to remove any of these if you don't need them
  #########################################################

  # Packaging
  - sphinx
  - pytest
  - pre_commit

  # Numeric Libs
  - numba >= 0.56.4
  - xarray >= 2023.3.0
  - dask
  - einops >= 0.6

  # IO
  - hdf5 >= 1.13.0
  - h5netcdf >= 1.1.0

  # ML and Misc
  - jupyter
  - wandb >= 0.13
  - scikit-learn >= 1.1

  # Visualization
  - matplotlib >= 3.6
  - imageio
  - moviepy
  - cartopy >= 0.21
  - ffmpeg >= 5.1
  - anaconda::graphviz
